<span style='color:yellow'> compalete end to end machine learing project </span>

In [40]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [41]:
df = sns.load_dataset('titanic')

In [42]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [43]:
df['family'] = df['sibsp'] + df['parch']

In [64]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.pipeline import Pipeline,make_pipeline
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LogisticRegression
from sklearn.impute import SimpleImputer
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score

In [45]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,family
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,1
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,1
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,0
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,1
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,0

In [46]:
x = df[['pclass','sex','age','fare','class','adult_male','embark_town','family']]
y = df[['survived']]

In [47]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42,shuffle=True)

In [48]:
x_train

     pclass     sex   age      fare   class  adult_male  embark_town  family
331       1    male  45.5   28.5000   First        True  Southampton       0
733       2    male  23.0   13.0000  Second        True  Southampton       0
382       3    male  32.0    7.9250   Third        True  Southampton       0
704       3    male  26.0    7.8542   Third        True  Southampton       1
813       3  female   6.0   31.2750   Third       False  Southampton       6
..      ...     ...   ...       ...     ...         ...          ...     ...
106       3  female  21.0    7.6500   Third       False  Southampton       0
270       1    male   NaN   31.0000   First        True  Southampton       0
860       3    male  41.0   14.1083   Third        True  Southampton       2
435       1  female  14.0  120.0000   First       False  Southampton       3
102       1    male  21.0   77.2875   First        True  Southampton       1

[712 rows x 8 columns]

In [49]:
x_test

     pclass     sex   age     fare   class  adult_male  embark_town  family
709       3    male   NaN  15.2458   Third        True    Cherbourg       2
439       2    male  31.0  10.5000  Second        True  Southampton       0
840       3    male  20.0   7.9250   Third        True  Southampton       0
720       2  female   6.0  33.0000  Second       False  Southampton       1
39        3  female  14.0  11.2417   Third       False    Cherbourg       1
..      ...     ...   ...      ...     ...         ...          ...     ...
433       3    male  17.0   7.1250   Third        True  Southampton       0
773       3    male   NaN   7.2250   Third        True    Cherbourg       0
25        3  female  38.0  31.3875   Third       False  Southampton       6
84        2  female  17.0  10.5000  Second       False  Southampton       0
10        3  female   4.0  16.7000   Third       False  Southampton       2

[179 rows x 8 columns]

In [50]:
y_train

     survived
331         0
733         0
382         0
704         0
813         0
..        ...
106         1
270         0
860         0
435         1
102         0

[712 rows x 1 columns]

In [51]:
y_test

     survived
709         1
439         0
840         0
720         1
39          1
..        ...
433         0
773         0
25          1
84          1
10          1

[179 rows x 1 columns]

In [52]:
x_train.columns

Index(['pclass', 'sex', 'age', 'fare', 'class', 'adult_male', 'embark_town',
       'family'],
      dtype='object')

In [53]:
numerical_data = ['pclass','age','fare','family']
categorical_data = ['sex','class','embark_town','adult_male']

In [54]:
numerical_pipeline = Pipeline(steps=[
    ('impute',SimpleImputer(strategy='median')),
     ('scaler',StandardScaler())
])

In [55]:
categorical_pipeline = Pipeline(steps=[
    ('impute',SimpleImputer(strategy='most_frequent')),
    ('encode',OneHotEncoder(handle_unknown='ignore'))
])

In [56]:
column_wise_transformation = ColumnTransformer(transformers=[
    ('numerical',numerical_pipeline,numerical_data),
    ('cat',categorical_pipeline,categorical_data)
])

In [57]:
model_pipeline = Pipeline(steps=[
    ('transform',column_wise_transformation),
    ('model',LogisticRegression())
])

In [58]:
model_pipeline.fit(x_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

Pipeline(steps=[('transform',
                 ColumnTransformer(transformers=[('numerical',
                                                  Pipeline(steps=[('impute',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['pclass', 'age', 'fare',
                                                   'family']),
                                                 ('cat',
                                                  Pipeline(steps=[('impute',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encode',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['sex', 'class',
                                                   'embark_town',
                                                   'adult_male'])])),
                ('model', LogisticRegression())])

In [ ]:
y_predict = model_pipeline.predict(x_test)
print(f'accuracy_score of model is{accuracy_score(y_test,y_predict)}')

accuracy_score of model is0.8044692737430168

In [65]:
from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test, y_predict))
print(classification_report(y_test, y_predict))

[[91 14]
 [21 53]]
              precision    recall  f1-score   support

           0       0.81      0.87      0.84       105
           1       0.79      0.72      0.75        74

    accuracy                           0.80       179
   macro avg       0.80      0.79      0.80       179
weighted avg       0.80      0.80      0.80       179